//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nox.Configuration.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SolutionNameEmpty {
            get {
                return ResourceManager.GetString("SolutionNameEmpty", resourceCulture);
            }
        }
        
        internal static string EnvironmentNameEmpty {
            get {
                return ResourceManager.GetString("EnvironmentNameEmpty", resourceCulture);
            }
        }
        
        internal static string EnvironmentNameDuplicate {
            get {
                return ResourceManager.GetString("EnvironmentNameDuplicate", resourceCulture);
            }
        }
        
        internal static string VersionControlProviderEmpty {
            get {
                return ResourceManager.GetString("VersionControlProviderEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlHostEmpty {
            get {
                return ResourceManager.GetString("VersionControlHostEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlSourceFolderEmpty {
            get {
                return ResourceManager.GetString("VersionControlSourceFolderEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlContainersFolderEmpty {
            get {
                return ResourceManager.GetString("VersionControlContainersFolderEmpty", resourceCulture);
            }
        }
        
        internal static string TeamUserNameEmpty {
            get {
                return ResourceManager.GetString("TeamUserNameEmpty", resourceCulture);
            }
        }
        
        internal static string TeamRolesEmpty {
            get {
                return ResourceManager.GetString("TeamRolesEmpty", resourceCulture);
            }
        }
        
        internal static string DomainEntitiesEmpty {
            get {
                return ResourceManager.GetString("DomainEntitiesEmpty", resourceCulture);
            }
        }
        
        internal static string EntityNameEmpty {
            get {
                return ResourceManager.GetString("EntityNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityNameDuplicate {
            get {
                return ResourceManager.GetString("EntityNameDuplicate", resourceCulture);
            }
        }
        
        internal static string TeamUserNameDuplicate {
            get {
                return ResourceManager.GetString("TeamUserNameDuplicate", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipNameEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipNameDuplicate {
            get {
                return ResourceManager.GetString("EntityRelationshipNameDuplicate", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipDescriptionEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipDescriptionEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipRelationshipEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipRelationshipEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipEntityEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipEntityEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipEntityMissing {
            get {
                return ResourceManager.GetString("EntityRelationshipEntityMissing", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipNameEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipNameDuplicate {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipNameDuplicate", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipDescriptionEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipDescriptionEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipRelationshipEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipRelationshipEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipEntityEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipEntityEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipEntityMissing {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipEntityMissing", resourceCulture);
            }
        }
        
        internal static string DomainQueryNameEmpty {
            get {
                return ResourceManager.GetString("DomainQueryNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryResponseOutputEmpty {
            get {
                return ResourceManager.GetString("DomainQueryResponseOutputEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryRequestNameEmpty {
            get {
                return ResourceManager.GetString("DomainQueryRequestNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryRequestTypeEmpty {
            get {
                return ResourceManager.GetString("DomainQueryRequestTypeEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryNameDuplicate {
            get {
                return ResourceManager.GetString("DomainQueryNameDuplicate", resourceCulture);
            }
        }
        
        internal static string DomainQueryResponseNameEmpty {
            get {
                return ResourceManager.GetString("DomainQueryResponseNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryResponseTypeEmpty {
            get {
                return ResourceManager.GetString("DomainQueryResponseTypeEmpty", resourceCulture);
            }
        }
        
        internal static string CollectionTypeOptionsNameEmpty {
            get {
                return ResourceManager.GetString("CollectionTypeOptionsNameEmpty", resourceCulture);
            }
        }
        
        internal static string CollectionTypeOptionsTypeEmpty {
            get {
                return ResourceManager.GetString("CollectionTypeOptionsTypeEmpty", resourceCulture);
            }
        }
        
        internal static string ObjectTypeOptionsAttributesEmpty {
            get {
                return ResourceManager.GetString("ObjectTypeOptionsAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string DomainCommandNameEmpty {
            get {
                return ResourceManager.GetString("DomainCommandNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainCommandNameDuplicate {
            get {
                return ResourceManager.GetString("DomainCommandNameDuplicate", resourceCulture);
            }
        }
        
        internal static string DomainCommandTypeEmpty {
            get {
                return ResourceManager.GetString("DomainCommandTypeEmpty", resourceCulture);
            }
        }
        
        internal static string SimpleTypeNameEmpty {
            get {
                return ResourceManager.GetString("SimpleTypeNameEmpty", resourceCulture);
            }
        }
        
        internal static string SimpleTypeTypeEmpty {
            get {
                return ResourceManager.GetString("SimpleTypeTypeEmpty", resourceCulture);
            }
        }
        
        internal static string EntityAttributesEmpty {
            get {
                return ResourceManager.GetString("EntityAttributesEmpty", resourceCulture);
            }
        }
    }
}
