//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nox.Configuration.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SolutionNameEmpty {
            get {
                return ResourceManager.GetString("SolutionNameEmpty", resourceCulture);
            }
        }
        
        internal static string EnvironmentNameEmpty {
            get {
                return ResourceManager.GetString("EnvironmentNameEmpty", resourceCulture);
            }
        }
        
        internal static string EnvironmentNameDuplicate {
            get {
                return ResourceManager.GetString("EnvironmentNameDuplicate", resourceCulture);
            }
        }
        
        internal static string VersionControlProviderEmpty {
            get {
                return ResourceManager.GetString("VersionControlProviderEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlHostEmpty {
            get {
                return ResourceManager.GetString("VersionControlHostEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlSourceFolderEmpty {
            get {
                return ResourceManager.GetString("VersionControlSourceFolderEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlContainersFolderEmpty {
            get {
                return ResourceManager.GetString("VersionControlContainersFolderEmpty", resourceCulture);
            }
        }
        
        internal static string TeamUserNameEmpty {
            get {
                return ResourceManager.GetString("TeamUserNameEmpty", resourceCulture);
            }
        }
        
        internal static string TeamRolesEmpty {
            get {
                return ResourceManager.GetString("TeamRolesEmpty", resourceCulture);
            }
        }
        
        internal static string DomainEntitiesEmpty {
            get {
                return ResourceManager.GetString("DomainEntitiesEmpty", resourceCulture);
            }
        }
    }
}
